Fix conditional CXX flags for 24.04 or later
Uses /bin/sh to correctly detect the distro from /etc/lsb-release.
Introduces a dependency on bc.

diff --git a/deps/igc/Makefile b/deps/igc/Makefile
--- a/deps/igc/Makefile
+++ b/deps/igc/Makefile
@@ -29,7 +29,7 @@ all: clone_deps patch build install
 clone_deps:
 	# Ephemerally clone or update if already exists.
 
-	@set -eux; \
+	@set -x; \
 	if [ ! -d "$(IGC_DIR)/.git" ]; then \
 		echo "Cloning IGC repository..."; \
 		git clone --recursive https://github.com/intel/intel-graphics-compiler.git $(IGC_DIR); \
@@ -80,35 +80,51 @@ $(PATCH_MARKER):
 build: clone_deps patch $(PREFIX)/igc/lib/libiga64.a
 
 $(PREFIX)/igc/lib/libiga64.a:
-	@set -eux; \
+	@set -x; \
 	rm -rf $(BUILD_DIR); \
 	mkdir -p $(BUILD_DIR); \
-	if [[ ! -f /etc/lsb-release ]]; then \
+	if [ ! -f /etc/lsb-release ]; then \
 	    printf "error: missing distribution identifier at /etc/lsb-release for customizing igc build.\n"; \
 		exit 1; \
 	fi; \
 	. /etc/lsb-release; \
 	readonly DISTRIB_RELEASE; \
-	major=${version%%.*}; \
-	minor=${version##*.}; \
-	if (( major > 24 || (major == 24 && minor >= 4) )); then \
-	    echo "$version is greater than or equal to 24.04"; \
-		cxx_flags="-Wno-maybe-uninitialized -Wno-uninitialized -Wno-free-nonheap-object -Wno-nonnull"; \
+	echo "$${DISTRIB_RELEASE}"; \
+	version="$${DISTRIB_RELEASE}"; \
+	if ! command -v bc >/dev/null 2>&1; then \
+		echo "Error: 'bc' is not installed." >&2; \
+		exit 1; \
+	fi; \
+	val=$$(echo "$$version <= 22.04" | bc); \
+	if [ "$$val" -eq 1 ]; then \
+	    echo "$$version is less than or equal to 22.04"; \
+		cxx_flags=; \
 	else \
-	    echo "$version is less than 24.04"; \
-        cxx_flags=""; \
+	    echo "$$version is greater than 22.04"; \
+		cxx_flags="-Wno-maybe-uninitialized -Wno-uninitialized -Wno-free-nonheap-object -Wno-nonnull"; \
 	fi; \
 	readonly cxx_flags; \
 	cd $(BUILD_DIR); \
-	cmake \
-		-DCMAKE_VERBOSE_MAKEFILE=ON \
-		-DCMAKE_BUILD_TYPE=$(BUILD_TYPE) \
-		-DCMAKE_CXX_FLAGS="${cxx_flags:-}" \
-		-DIGC_OPTION__LLVM_MODE=Source \
-		-DIGC_OPTION__LLVM_SOURCES_DIR=$(BASEDIR)/llvm-project \
-		-DIGC_OPTION__LLVM_PREFERRED_VERSION=14.0.5 \
-		-DCMAKE_INSTALL_PREFIX=$(PREFIX)/igc \
-		$(IGC_DIR); \
+	if [ "$${cxx_flags}" = "" ]; then \
+		cmake \
+			-DCMAKE_VERBOSE_MAKEFILE=ON \
+			-DCMAKE_BUILD_TYPE=$(BUILD_TYPE) \
+			-DIGC_OPTION__LLVM_MODE=Source \
+			-DIGC_OPTION__LLVM_SOURCES_DIR=$(BASEDIR)/llvm-project \
+			-DIGC_OPTION__LLVM_PREFERRED_VERSION=14.0.5 \
+			-DCMAKE_INSTALL_PREFIX=$(PREFIX)/igc \
+			$(IGC_DIR); \
+	else \
+		cmake \
+			-DCMAKE_VERBOSE_MAKEFILE=ON \
+			-DCMAKE_BUILD_TYPE=$(BUILD_TYPE) \
+			-DCMAKE_CXX_FLAGS="\"$${cxx_flags}\"" \
+			-DIGC_OPTION__LLVM_MODE=Source \
+			-DIGC_OPTION__LLVM_SOURCES_DIR=$(BASEDIR)/llvm-project \
+			-DIGC_OPTION__LLVM_PREFERRED_VERSION=14.0.5 \
+			-DCMAKE_INSTALL_PREFIX=$(PREFIX)/igc \
+			$(IGC_DIR); \
+	fi; \
 	sed -i 's/-fbracket-depth=512//g' IGC/Compiler/CMakeFiles/Compiler.dir/flags.make; \
 	$(MAKE) -j$(shell nproc);
 
